import Head from 'next/head'
import Image from 'next/image'

import { CloudinaryImage } from '@cloudinary/url-gen';
import { AdvancedImage, responsive } from '@cloudinary/react';

import styles from '../styles/Home.module.css'

export default function Home() {
  const cloudinaryImage = new CloudinaryImage('insblzwyr53tqasswcdz', {
    cloudName: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  })
    .format('auto')
    .quality('auto');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AdvancedImage
          alt="Colby"
          cldImg={cloudinaryImage}
          plugins={[responsive()]}
        />
      </main>
    </div>
  )
}
